//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TriggerPinchy : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerPinchedLeft
        {
            get
            {
                return SteamVR_Actions.triggerPinchy_TriggerPinchedLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerPinchedRight
        {
            get
            {
                return SteamVR_Actions.triggerPinchy_TriggerPinchedRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadClickedLeft
        {
            get
            {
                return SteamVR_Actions.triggerPinchy_TrackpadClickedLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadClickedRight
        {
            get
            {
                return SteamVR_Actions.triggerPinchy_TrackpadClickedRight;
            }
        }
    }
}
